workflows:
  android-workflow:
    name: AlSharq
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Build
        script: |
          chmod +x ./build.sh
          ./build.sh
    artifacts:
      - app/build/outputs/apk/debug/*.apk
